services:
  intro_opengl:
    build: .
    volumes:
      - .:/usr/src/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8080:8080"
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}